### ISSUE TITLE
investigate io.grpc 1.63/1.64 issues in integration tests

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko-grpc#310]
We're currently stuck on v1.62.

https://github.com/grpc/grpc-java/issues/11082

see also #271

**Comment by pjfanning** [comment]
@raboof we seem to have no test failures - unlike with #271 

If this looks ok, I can remove the scalasteward pin that keeps us on grpc 1.62.

**Comment by raboof** [comment]
> @raboof we seem to have no test failures in #311 - unlike with #271
> 
> If this looks ok, I can remove the scalasteward pin that keeps us on grpc 1.62.

Awesome. I haven't looked closer, but let's trust the tests and remove that pin.
