### ISSUE TITLE
`pekko-grpc-sbt-plugin` has a strange artifact ID.

### ISSUE THREAD

**Issue by Roiocam** [apache/pekko-grpc#326]
https://repository.apache.org/content/groups/staging/org/apache/pekko/pekko-grpc-sbt-plugin_2.12_1.0/

don't know why it contain `_1.0`

**Comment by raboof** [comment]
This is the format for SBT plugins, I think the '1.0' refers to the current `1.x` sbt version line

**Comment by Roiocam** [comment]
> This is the format for SBT plugins, I think the '1.0' refers to the current `1.x` sbt version line

Thanks for the explanation, the index seems fine.

https://central.sonatype.com/search?q=pekko-grpc-sbt-plugin
