### ISSUE TITLE
Is there a roadmap for release 1.1.x?

### ISSUE THREAD

**Issue by hacetin** [apache/pekko-grpc#373]
Other pekko libraries released [version 1.1.x](https://mvnrepository.com/artifact/org.apache.pekko/pekko-actor_3/1.1.0) around a month ago. Is there a roadmap for pekko-grpc for the new release?

**Comment by pjfanning** [comment]
Releases are discussed on the dev@pekko.apache.org mailing list - ASF rules.

https://lists.apache.org/thread/mpwxxpqcc30cly3z0kmct0qnrz4g46j3

Pekko gRPC 1.1.0-RC1 should be ready to go when Pekko HTTP 1.1.0 is fully released.

**Comment by hacetin** [comment]
Thanks @pjfanning
