### ISSUE TITLE
Incorrect import statements generated from GRPC plugin

### ISSUE THREAD

**Issue by sfali23** [apache/pekko-grpc#410]
It seems that GRPC plugin generated code has generated incorrect import statements, look at the following generated code `org.apache` is missing from the imports which is causing to fail at compile time. I am using Scala 3 and Pekko GRPC 1.1.0.

```
import scala.concurrent.ExecutionContext

import org.apache.pekko
import pekko.grpc.scaladsl.{ GrpcExceptionHandler, GrpcMarshalling }
import pekko.grpc.Trailers

import pekko.actor.ActorSystem
import pekko.actor.ClassicActorSystemProvider
import pekko.annotation.ApiMayChange
import pekko.http.scaladsl.model
import pekko.stream.{Materializer, SystemMaterializer}

import pekko.grpc.internal.TelemetryExtension

import pekko.grpc.PekkoGrpcGenerated
```

Regards,

Syed

**Comment by pjfanning** [comment]
If you get a compile issue, maybe you should report it to Scala3 team.

**Comment by sfali23** [comment]
Sorry my bad, I was having Pekko version mismatch and excluded all `org.apache.pekko` dependencies from grpc runtime and forgot to add individual dependencies.
